spring:
  application:
    name: rpalace
  security:
    oauth2:
      resource:
        filter-order: 3
      client:
        registration:
          reddit:
            client-id: ${RPALACE_REDDIT_CLIENT_ID}
            client-secret: ${RPALACE_REDDIT_CLIENT_SECRET}
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/oauth2/callback # NOTE: Insert your own redirect URI for Reddit, e.g https://<host:port>/oauth2/callback
            scope: history, save, read, mysubreddits, identity
            client-name: rpalace-client
        provider:
          reddit:
            authorization-uri: https://www.reddit.com/api/v1/authorize?duration=permanent
            token-uri: https://www.reddit.com/api/v1/access_token
  datasource:
    url: ${RPALACE_DB_URL}
    username: ${RPALACE_DB_USER}
    password: ${RPALACE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_schema: rpalace_schema
    hibernate:
      ddl-auto: update
  redis:
    host: localhost # NOTE: Insert your own Redis host
    port: 6379 # NOTE: Insert your own Redis port
server:
  port: 8090
rpalace:
  user-agent: 'web:rpalace:v.0.0.1-SNAPSHOT'
  reddit:
    api-base-uri: https://oauth.reddit.com
  jwt:
    secret-file: ${RPALACE_JWT_SECRET}
    pub-file: ${RPALACE_JWT_PUB}
  encipher:
    file: ${RPALACE_ENCIPHER}
logging:
  level:
    org:
      kushtrimhajrizi:
        rpalace: INFO
